language: c++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - emscripten
            - g++-6
            - gcc-6
            - cmake
            - cmake-data
            - libx11-xcb-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
            - libudev-dev
            - libopenal-dev
            - freeglut3-dev
            - libjpeg-dev
            - libfreetype6-dev
            - libxrandr-dev
            - libglew-dev
            - libsndfile1-dev
            - libasound2-dev 
            - alsa-utils 
            - alsa-oss

git:
  submodules: false

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - git submodule update --init --recursive
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE="/usr/lib/emscripten/cmake/Modules/Platform/Emscripten.cmake" ..
  - make -j2